// Unsubscribe plumbing for the transactional emails in lib/email.ts.
//
// The link in an email has to work for someone who is not signed in (that's the whole point of
// an unsubscribe), so it can't rely on a session. Instead each link carries an HMAC-SHA256 token
// over `userId.kind`, signed with NEXTAUTH_SECRET. That gives us an unforgeable, stateless
// capability scoped to exactly one user + one notification type — no extra token table, and
// nothing to expire (an unsubscribe link in a two-year-old email should still work).
//
// Unsubscribing flips the same per-user setting the settings page exposes, so the two views can
// never disagree and the user can re-subscribe from the UI.
//
// This module is deliberately DB-free: lib/email.ts needs the link builders and the kind list,
// while the code that actually flips those per-module settings lives in lib/emailUnsubscribeStore.
// Keeping them apart breaks what would otherwise be an import cycle — email -> unsubscribe ->
// each module's db -> that module's notification code -> email.

import { createHmac, timingSafeEqual } from 'crypto';
import { appBaseUrl } from '@/lib/appUrl';

// One kind per notification the app can send. `all` is not a sendable kind — it only appears in
// unsubscribe links generated by the "turn everything off" button on the unsubscribe page.
export const UNSUBSCRIBE_KINDS = [
  'quest-digest',
  'quest-bonus',
  'quest-reminder',
  'rune-digest',
  'forage-checkin',
] as const;

export type EmailKind = (typeof UNSUBSCRIBE_KINDS)[number];
export type UnsubscribeTarget = EmailKind | 'all';

export const KIND_LABELS: Record<UnsubscribeTarget, string> = {
  'quest-digest': 'Quest daily digest',
  'quest-bonus': 'Quest bonus task notification',
  'quest-reminder': 'Quest task reminders',
  'rune-digest': 'Rune daily review',
  'forage-checkin': 'Forage weekly check-in reminder',
  all: 'All Grimoire notification emails',
};

function isEmailKind(value: string): value is EmailKind {
  return (UNSUBSCRIBE_KINDS as readonly string[]).includes(value);
}

// ---------------------------------------------------------------- token

function signingSecret(): string {
  const secret = process.env.NEXTAUTH_SECRET;
  if (!secret) throw new Error('NEXTAUTH_SECRET is required to sign unsubscribe tokens');
  return secret;
}

function base64url(input: Buffer | string): string {
  return Buffer.from(input).toString('base64url');
}

function signature(payload: string): string {
  return createHmac('sha256', signingSecret()).update(payload).digest('base64url');
}

export function signUnsubscribeToken(userId: string, kind: UnsubscribeTarget): string {
  const payload = `${userId}.${kind}`;
  return `${base64url(payload)}.${signature(payload)}`;
}

export interface VerifiedUnsubscribe {
  userId: string;
  kind: UnsubscribeTarget;
}

// Returns null for anything malformed, tampered with, or signed by a different secret.
export function verifyUnsubscribeToken(token: string): VerifiedUnsubscribe | null {
  const parts = token.split('.');
  if (parts.length !== 2) return null;
  const [encodedPayload, provided] = parts;

  let payload: string;
  try {
    payload = Buffer.from(encodedPayload, 'base64url').toString('utf8');
  } catch {
    return null;
  }

  const expected = signature(payload);
  const providedBuf = Buffer.from(provided);
  const expectedBuf = Buffer.from(expected);
  // Length check first: timingSafeEqual throws on a length mismatch.
  if (providedBuf.length !== expectedBuf.length) return null;
  if (!timingSafeEqual(providedBuf, expectedBuf)) return null;

  const separator = payload.lastIndexOf('.');
  if (separator <= 0) return null;
  const userId = payload.slice(0, separator);
  const kind = payload.slice(separator + 1);
  if (kind !== 'all' && !isEmailKind(kind)) return null;
  return { userId, kind: kind as UnsubscribeTarget };
}

// Human-facing link put in the email body: opens a page that says what will be turned off and
// asks for a click, so a link-scanning proxy can't silently unsubscribe someone.
export function buildUnsubscribeUrl(userId: string, kind: UnsubscribeTarget): string {
  return `${appBaseUrl()}/unsubscribe?token=${encodeURIComponent(signUnsubscribeToken(userId, kind))}`;
}

// Machine-facing target for the RFC 8058 List-Unsubscribe header. Mail clients POST to this
// directly, so it must act immediately rather than render a confirmation page.
export function buildUnsubscribeApiUrl(userId: string, kind: UnsubscribeTarget): string {
  return `${appBaseUrl()}/api/email/unsubscribe?token=${encodeURIComponent(signUnsubscribeToken(userId, kind))}`;
}
