-- Populate equipment.image_url (sourced via web search, 2026-07-06). Not part of the
-- authoritative seed/init script since these are external URLs applied to already-seeded rows.
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/8/85/Olympic_barbell.jpg', modified_at = GETDATE() WHERE name = N'Barbells';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/1/15/EZ-%D1%88%D1%82%D0%B0%D0%BD%D0%B3%D0%B0_Torneo.jpg', modified_at = GETDATE() WHERE name = N'EZ Curl Bar';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/9/9f/Trap_bar_%28horizontal%29.jpg', modified_at = GETDATE() WHERE name = N'Trap Bar';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/a/a2/Weight_plate.jpg', modified_at = GETDATE() WHERE name = N'Weight Plates';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/7/7f/Captains_chair.jpg', modified_at = GETDATE() WHERE name = N'Captain''s Chair';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/2/25/Dip_and_pull-up_machine.jpg', modified_at = GETDATE() WHERE name = N'Pull Up Bar';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/a/a3/Powerrack.jpg', modified_at = GETDATE() WHERE name = N'Squat Rack';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/6/6c/WeightBenchFront.jpg', modified_at = GETDATE() WHERE name = N'Flat Bench';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/7/7a/Incline_bench.jpg', modified_at = GETDATE() WHERE name = N'Incline Bench';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/c/cc/Negative_bench.jpg', modified_at = GETDATE() WHERE name = N'Decline Bench';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/c/cc/PreacherBenchBicepsCurl.JPG', modified_at = GETDATE() WHERE name = N'Vertical Bench';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/8/8f/Personal_Training_at_a_Gym_-_Cable_Crossover.JPG', modified_at = GETDATE() WHERE name = N'Crossover Cable';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/6/68/Lat_pulldown_machine_20180112.jpg', modified_at = GETDATE() WHERE name = N'Lat Pulldown';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/8/82/CableMachineUprightRow.JPG', modified_at = GETDATE() WHERE name = N'Hi-Lo Pulley';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/2/2d/Cable-seated-rows-1.png', modified_at = GETDATE() WHERE name = N'Row Cable';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/1/12/Triceps-pushdown-with-rope-1.gif', modified_at = GETDATE() WHERE name = N'Rope Cable';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/a/a3/CrossFit_workout_on_SkiErg_DSC1807.jpg', modified_at = GETDATE() WHERE name = N'Ski Erg';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/1/1f/Treadmill_from_Viking_Sport%2C_front.jpg', modified_at = GETDATE() WHERE name = N'Treadmill';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/c/ce/Stationary_bicycle.jpg', modified_at = GETDATE() WHERE name = N'Stationary Bike';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/c/ce/Concept2_D%E5%9E%8B%E5%88%92%E8%88%B9%E5%99%A8.jpg', modified_at = GETDATE() WHERE name = N'Rowing Machine';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/d/da/Elliptical_machine.jpg', modified_at = GETDATE() WHERE name = N'Elliptical';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/d/d0/Stair_machine.jpg', modified_at = GETDATE() WHERE name = N'Stair Stepper';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/4/47/Assault_Bike_Spartan_Games_2.jpg', modified_at = GETDATE() WHERE name = N'Air Bike';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/8/87/Ab_wheel.jpg', modified_at = GETDATE() WHERE name = N'Ab Wheel';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/3/34/Battling_ropes.jpg', modified_at = GETDATE() WHERE name = N'Battle Ropes';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/a/ae/Anillas.jpg', modified_at = GETDATE() WHERE name = N'Gymnastic Rings';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/f/fa/SpeedRope.jpg', modified_at = GETDATE() WHERE name = N'Jump Rope';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/8/8f/Brine_lax_ball.jpg', modified_at = GETDATE() WHERE name = N'Lacrosse Ball';
UPDATE equipment SET image_url = N'https://assets.roguefitness.com/f_auto,q_auto,c_limit,w_768,b_rgb:f8f8f8/catalog/Strength%20Equipment/Strength%20Training/Upper%20Body%20Training/XX5477/RA0017-H_vhbu2k.png', modified_at = GETDATE() WHERE name = N'Landmine Attachment';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/2/23/Plastic_tubing.jpg', modified_at = GETDATE() WHERE name = N'PVC Pipe';
UPDATE equipment SET image_url = N'https://assets.roguefitness.com/f_auto,q_auto,c_limit,w_768,b_rgb:f8f8f8/catalog/Strength%20Equipment/Strength%20Training/Sleds/XX847/XX847-H_arrguc.png', modified_at = GETDATE() WHERE name = N'Sled';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/2/29/Exercise_ball.jpg', modified_at = GETDATE() WHERE name = N'Stability Ball';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Tyre_Flip_equipment.jpg/960px-Tyre_Flip_equipment.jpg', modified_at = GETDATE() WHERE name = N'Tire';
UPDATE equipment SET image_url = N'https://assets.roguefitness.com/f_auto,q_auto,c_limit,w_768,b_rgb:f8f8f8/catalog/Strength%20Equipment/Strength%20Training/Upper%20Body%20Training/RWRISTROLLER/RWRISTROLLER-H_rbjtil.png', modified_at = GETDATE() WHERE name = N'Wrist Roller';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/3/31/Wa%C5%82ek_do_masa%C5%BCu3.jpg', modified_at = GETDATE() WHERE name = N'Foam Roller';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/6/6d/Yoga_mat.jpg', modified_at = GETDATE() WHERE name = N'Yoga Mat';
UPDATE equipment SET image_url = N'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_361,h_361,b_rgb:f8f8f8/catalog/Conditioning/Plyo%20Boxes%20/Games%20Boxes/RA0368/RA0368-TH_f0sza9.png', modified_at = GETDATE() WHERE name = N'Plyo Box';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/c/cd/Fitness_bar_with_resistance_tube.jpg', modified_at = GETDATE() WHERE name = N'Handle Bands';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/c/cf/Strength_band.png', modified_at = GETDATE() WHERE name = N'Loop Bands';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/b/be/Dumbbell.JPG', modified_at = GETDATE() WHERE name = N'Dumbbells';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/3/31/8kg_kettlebell.jpg', modified_at = GETDATE() WHERE name = N'Kettlebells';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/6/62/Medicine_Ball_1_2017-01-13.jpg', modified_at = GETDATE() WHERE name = N'Medicine Balls';
UPDATE equipment SET image_url = N'https://strengthwarehouseusa.com/cdn/shop/files/body-solid-ab-crunch-machine_700x700.jpg?v=1759155364', modified_at = GETDATE() WHERE name = N'Ab Crunch Machine';
UPDATE equipment SET image_url = N'https://titan.fitness/cdn/shop/files/401855_01.jpg?v=1706742058&width=1946', modified_at = GETDATE() WHERE name = N'Assisted Pull-Up Machine';
UPDATE equipment SET image_url = N'https://titan.fitness/cdn/shop/files/401864_01.jpg?v=1724857600&width=1946', modified_at = GETDATE() WHERE name = N'Belt Squat Machine';
UPDATE equipment SET image_url = N'https://titan.fitness/cdn/shop/files/400789_01.jpg?v=1776803997&width=1946', modified_at = GETDATE() WHERE name = N'Bicep Curl Machine';
UPDATE equipment SET image_url = N'https://titan.fitness/cdn/shop/files/401473_01.jpg?v=1779301563&width=1946', modified_at = GETDATE() WHERE name = N'Calf Raise Machine';
UPDATE equipment SET image_url = N'https://titan.fitness/cdn/shop/files/400788_01.jpg?v=1758046947&width=1946', modified_at = GETDATE() WHERE name = N'Chest Press Machine';
UPDATE equipment SET image_url = N'https://titan.fitness/cdn/shop/files/400939_01.jpg?v=1706747023&width=1946', modified_at = GETDATE() WHERE name = N'GHD Machine';
UPDATE equipment SET image_url = N'https://titan.fitness/cdn/shop/files/401438_01.jpg?v=1774024300&width=1946', modified_at = GETDATE() WHERE name = N'Glute Kickback Machine';
UPDATE equipment SET image_url = N'https://titan.fitness/cdn/shop/files/401231_01.jpg?v=1779301309&width=1946', modified_at = GETDATE() WHERE name = N'Hack Squat Machine';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/f/f9/Hip_abductor_machine.jpg', modified_at = GETDATE() WHERE name = N'Hip Abduction Machine';
UPDATE equipment SET image_url = N'https://titan.fitness/cdn/shop/files/401784_01.jpg?v=1764178172&width=1946', modified_at = GETDATE() WHERE name = N'Hip Adduction Machine';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/c/c6/LyingLegCurlMachineExercise.JPG', modified_at = GETDATE() WHERE name = N'Leg Curl Machine';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/3/36/LegExtensionMachineExercise.JPG', modified_at = GETDATE() WHERE name = N'Leg Extension Machine';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/2/2d/Leg_press_machine.jpg', modified_at = GETDATE() WHERE name = N'Leg Press Machine';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/7/7e/Butterfly-machine-1.png', modified_at = GETDATE() WHERE name = N'Pec Deck';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/0/0a/Woman_using_a_seated_cable_row_machine_at_the_gym.jpg', modified_at = GETDATE() WHERE name = N'Seated Row Machine';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/2/23/Shoulder_Press.jpg', modified_at = GETDATE() WHERE name = N'Shoulder Press Machine';
UPDATE equipment SET image_url = N'https://upload.wikimedia.org/wikipedia/commons/7/74/Smith_machine.webp', modified_at = GETDATE() WHERE name = N'Smith Machine';
UPDATE equipment SET image_url = N'https://live.staticflickr.com/929/28957105537_c081fbb728_b.jpg', modified_at = GETDATE() WHERE name = N'Triceps Extension Machine';
