-- Repoint equipment.image_url from external hotlinks to locally self-hosted copies
-- (public/equipment/*) — avoids depending on Wikimedia/vendor hotlink tolerance and
-- rate limits discovered while verifying the initial external-URL version.
UPDATE equipment SET image_url = N'/equipment/barbells.jpg', modified_at = GETDATE() WHERE name = N'Barbells';
UPDATE equipment SET image_url = N'/equipment/ez-curl-bar.jpg', modified_at = GETDATE() WHERE name = N'EZ Curl Bar';
UPDATE equipment SET image_url = N'/equipment/trap-bar.jpg', modified_at = GETDATE() WHERE name = N'Trap Bar';
UPDATE equipment SET image_url = N'/equipment/weight-plates.jpg', modified_at = GETDATE() WHERE name = N'Weight Plates';
UPDATE equipment SET image_url = N'/equipment/captain-s-chair.jpg', modified_at = GETDATE() WHERE name = N'Captain''s Chair';
UPDATE equipment SET image_url = N'/equipment/pull-up-bar.jpg', modified_at = GETDATE() WHERE name = N'Pull Up Bar';
UPDATE equipment SET image_url = N'/equipment/squat-rack.jpg', modified_at = GETDATE() WHERE name = N'Squat Rack';
UPDATE equipment SET image_url = N'/equipment/flat-bench.jpg', modified_at = GETDATE() WHERE name = N'Flat Bench';
UPDATE equipment SET image_url = N'/equipment/incline-bench.jpg', modified_at = GETDATE() WHERE name = N'Incline Bench';
UPDATE equipment SET image_url = N'/equipment/decline-bench.jpg', modified_at = GETDATE() WHERE name = N'Decline Bench';
UPDATE equipment SET image_url = N'/equipment/vertical-bench.jpg', modified_at = GETDATE() WHERE name = N'Vertical Bench';
UPDATE equipment SET image_url = N'/equipment/crossover-cable.jpg', modified_at = GETDATE() WHERE name = N'Crossover Cable';
UPDATE equipment SET image_url = N'/equipment/lat-pulldown.jpg', modified_at = GETDATE() WHERE name = N'Lat Pulldown';
UPDATE equipment SET image_url = N'/equipment/hi-lo-pulley.jpg', modified_at = GETDATE() WHERE name = N'Hi-Lo Pulley';
UPDATE equipment SET image_url = N'/equipment/row-cable.png', modified_at = GETDATE() WHERE name = N'Row Cable';
UPDATE equipment SET image_url = N'/equipment/rope-cable.gif', modified_at = GETDATE() WHERE name = N'Rope Cable';
UPDATE equipment SET image_url = N'/equipment/ski-erg.jpg', modified_at = GETDATE() WHERE name = N'Ski Erg';
UPDATE equipment SET image_url = N'/equipment/treadmill.jpg', modified_at = GETDATE() WHERE name = N'Treadmill';
UPDATE equipment SET image_url = N'/equipment/stationary-bike.jpg', modified_at = GETDATE() WHERE name = N'Stationary Bike';
UPDATE equipment SET image_url = N'/equipment/rowing-machine.jpg', modified_at = GETDATE() WHERE name = N'Rowing Machine';
UPDATE equipment SET image_url = N'/equipment/elliptical.jpg', modified_at = GETDATE() WHERE name = N'Elliptical';
UPDATE equipment SET image_url = N'/equipment/stair-stepper.jpg', modified_at = GETDATE() WHERE name = N'Stair Stepper';
UPDATE equipment SET image_url = N'/equipment/air-bike.jpg', modified_at = GETDATE() WHERE name = N'Air Bike';
UPDATE equipment SET image_url = N'/equipment/ab-wheel.jpg', modified_at = GETDATE() WHERE name = N'Ab Wheel';
UPDATE equipment SET image_url = N'/equipment/battle-ropes.jpg', modified_at = GETDATE() WHERE name = N'Battle Ropes';
UPDATE equipment SET image_url = N'/equipment/gymnastic-rings.jpg', modified_at = GETDATE() WHERE name = N'Gymnastic Rings';
UPDATE equipment SET image_url = N'/equipment/jump-rope.jpg', modified_at = GETDATE() WHERE name = N'Jump Rope';
UPDATE equipment SET image_url = N'/equipment/lacrosse-ball.jpg', modified_at = GETDATE() WHERE name = N'Lacrosse Ball';
UPDATE equipment SET image_url = N'/equipment/landmine-attachment.jpg', modified_at = GETDATE() WHERE name = N'Landmine Attachment';
UPDATE equipment SET image_url = N'/equipment/pvc-pipe.jpg', modified_at = GETDATE() WHERE name = N'PVC Pipe';
UPDATE equipment SET image_url = N'/equipment/sled.jpg', modified_at = GETDATE() WHERE name = N'Sled';
UPDATE equipment SET image_url = N'/equipment/stability-ball.jpg', modified_at = GETDATE() WHERE name = N'Stability Ball';
UPDATE equipment SET image_url = N'/equipment/tire.jpg', modified_at = GETDATE() WHERE name = N'Tire';
UPDATE equipment SET image_url = N'/equipment/wrist-roller.jpg', modified_at = GETDATE() WHERE name = N'Wrist Roller';
UPDATE equipment SET image_url = N'/equipment/foam-roller.jpg', modified_at = GETDATE() WHERE name = N'Foam Roller';
UPDATE equipment SET image_url = N'/equipment/yoga-mat.jpg', modified_at = GETDATE() WHERE name = N'Yoga Mat';
UPDATE equipment SET image_url = N'/equipment/plyo-box.jpg', modified_at = GETDATE() WHERE name = N'Plyo Box';
UPDATE equipment SET image_url = N'/equipment/handle-bands.jpg', modified_at = GETDATE() WHERE name = N'Handle Bands';
UPDATE equipment SET image_url = N'/equipment/loop-bands.png', modified_at = GETDATE() WHERE name = N'Loop Bands';
UPDATE equipment SET image_url = N'/equipment/dumbbells.jpg', modified_at = GETDATE() WHERE name = N'Dumbbells';
UPDATE equipment SET image_url = N'/equipment/kettlebells.jpg', modified_at = GETDATE() WHERE name = N'Kettlebells';
UPDATE equipment SET image_url = N'/equipment/medicine-balls.jpg', modified_at = GETDATE() WHERE name = N'Medicine Balls';
UPDATE equipment SET image_url = N'/equipment/ab-crunch-machine.jpg', modified_at = GETDATE() WHERE name = N'Ab Crunch Machine';
UPDATE equipment SET image_url = N'/equipment/assisted-pull-up-machine.jpg', modified_at = GETDATE() WHERE name = N'Assisted Pull-Up Machine';
UPDATE equipment SET image_url = N'/equipment/belt-squat-machine.jpg', modified_at = GETDATE() WHERE name = N'Belt Squat Machine';
UPDATE equipment SET image_url = N'/equipment/bicep-curl-machine.jpg', modified_at = GETDATE() WHERE name = N'Bicep Curl Machine';
UPDATE equipment SET image_url = N'/equipment/calf-raise-machine.jpg', modified_at = GETDATE() WHERE name = N'Calf Raise Machine';
UPDATE equipment SET image_url = N'/equipment/chest-press-machine.jpg', modified_at = GETDATE() WHERE name = N'Chest Press Machine';
UPDATE equipment SET image_url = N'/equipment/ghd-machine.jpg', modified_at = GETDATE() WHERE name = N'GHD Machine';
UPDATE equipment SET image_url = N'/equipment/glute-kickback-machine.jpg', modified_at = GETDATE() WHERE name = N'Glute Kickback Machine';
UPDATE equipment SET image_url = N'/equipment/hack-squat-machine.jpg', modified_at = GETDATE() WHERE name = N'Hack Squat Machine';
UPDATE equipment SET image_url = N'/equipment/hip-abduction-machine.jpg', modified_at = GETDATE() WHERE name = N'Hip Abduction Machine';
UPDATE equipment SET image_url = N'/equipment/hip-adduction-machine.jpg', modified_at = GETDATE() WHERE name = N'Hip Adduction Machine';
UPDATE equipment SET image_url = N'/equipment/leg-curl-machine.jpg', modified_at = GETDATE() WHERE name = N'Leg Curl Machine';
UPDATE equipment SET image_url = N'/equipment/leg-extension-machine.jpg', modified_at = GETDATE() WHERE name = N'Leg Extension Machine';
UPDATE equipment SET image_url = N'/equipment/leg-press-machine.jpg', modified_at = GETDATE() WHERE name = N'Leg Press Machine';
UPDATE equipment SET image_url = N'/equipment/pec-deck.png', modified_at = GETDATE() WHERE name = N'Pec Deck';
UPDATE equipment SET image_url = N'/equipment/seated-row-machine.jpg', modified_at = GETDATE() WHERE name = N'Seated Row Machine';
UPDATE equipment SET image_url = N'/equipment/shoulder-press-machine.jpg', modified_at = GETDATE() WHERE name = N'Shoulder Press Machine';
UPDATE equipment SET image_url = N'/equipment/smith-machine.webp', modified_at = GETDATE() WHERE name = N'Smith Machine';
UPDATE equipment SET image_url = N'/equipment/triceps-extension-machine.jpg', modified_at = GETDATE() WHERE name = N'Triceps Extension Machine';
