// Maps alternate/informal exercise names (lowercase) to canonical seed exercise names.
// Used during CSV import to auto-match exercises that have different names in the user's data.
export const EXERCISE_NAME_ALIASES: Record<string, string> = {
  "1-arm cable rows": "One-Handed Cable Row",
  "1-arm lat pull downs": "One-Handed Lat Pulldown",
  "1-arm tricep pushdown": "Crossbody Cable Triceps Extension",
  "3 count pause bench": "Bench Press",
  "ab crunch machine": "Machine Crunch",
  "air squats": "Air Squat",
  "alternating db press": "Dumbbell Chest Press",
  "alternating hammer curl": "Hammer Curl",
  "archer pull up": "Pull-Up",
  "assisted chin up": "Assisted Chin-Up",
  "assisted pull up": "Assisted Pull-Up",
  "assisted wide grip pull up": "Assisted Pull-Up",
  "australian chin up": "Inverted Row with Underhand Grip",
  "back extensions": "Back Extension",
  "back raise": "Back Extension",
  "back raise holds": "Back Extension",
  "bar muscle up": "Muscle-Up (Bar)",
  "barbell bench press": "Bench Press",
  "barbell bicep drag curl": "Drag Curl",
  "barbell curls": "Barbell Curl",
  "barbell decline bench press": "Decline Bench Press",
  "barbell incline bench press": "Incline Bench Press",
  "barbell shoulder press": "Overhead Press",
  "barbell step up": "Step Up",
  "behind the back cable bicep curl": "Bayesian Curl",
  "behind the back cable lateral raise": "Cable Lateral Raise",
  "behind the neck push press": "Behind the Neck Press",
  "bent over barbell row": "Barbell Row",
  "bentover rows": "Barbell Row",
  "bicep curl on row machine": "Machine Bicep Curl",
  "bird dogs": "Dead Bug",
  "box front squat": "Front Squat",
  "cable bicep curl": "Cable Curl With Bar",
  "cable cross overs": "Standing Cable Chest Fly",
  "cable crossover flat bench fly": "Seated Cable Chest Fly",
  "cable crossover fly": "Standing Cable Chest Fly",
  "cable face pull": "Face Pull",
  "cable hip extension": "Cable Glute Kickback",
  "cable one arm tricep side extension": "Crossbody Cable Triceps Extension",
  "cable one arm underhand tricep extension": "Overhead Cable Triceps Extension (Low)",
  "cable pullover": "Straight Arm Lat Pulldown",
  "cable rear delt fly": "Reverse Cable Flyes",
  "cable rope hammer curls": "Cable Curl With Rope",
  "cable rope overhead triceps extension": "Overhead Cable Triceps Extension (Low)",
  "cable rope tricep extension": "Tricep Pushdown With Rope",
  "cable row": "Cable Close Grip Seated Row",
  "cable tricep pushdown": "Tricep Pushdown With Bar",
  "cable twist": "Core Twist",
  "cable upright row": "Barbell Upright Row",
  "cable wood chop": "High to Low Wood Chop with Cable",
  "calf press": "Calf Raise in Leg Press",
  "calf raises": "Standing Calf Raise",
  "chest dip": "Bar Dip",
  "chest supported rows": "Chest-Supported Dumbbell Row",
  "chin up": "Chin-Up",
  "chinup grip pulldowns": "Lat Pulldown With Supinated Grip",
  "clean deadlift": "Deadlift",
  "close-grip pushup": "Close-Grip Push-Up",
  "closegrip bench": "Close-Grip Bench Press",
  "closegrip pushup": "Close-Grip Push-Up",
  "comp bench": "Bench Press",
  "comp deadlift": "Deadlift",
  "comp squat": "Squat",
  "copenhagen plank (floor)": "Copenhagen Plank",
  "cross body hammer curls": "Hammer Curl",
  "cross body mountain climber": "Mountain Climbers",
  "crunches": "Crunch",
  "curl ups": "Crunch",
  "db bench": "Dumbbell Chest Press",
  "db bench w/ deep stretch": "Dumbbell Chest Press",
  "db curls": "Dumbbell Curl",
  "db fly": "Dumbbell Chest Fly",
  "db front raise": "Dumbbell Front Raise",
  "db lateral raise": "Dumbbell Lateral Raise",
  "db military press": "Dumbbell Shoulder Press",
  "db preacher curls": "Dumbbell Preacher Curl",
  "db rdls": "Dumbbell Romanian Deadlift",
  "db rows": "Dumbbell Row",
  "dead hang": "Bar Hang",
  "decline crunch": "Crunch",
  "decline push up": "Decline Push-Up",
  "decline russian twists": "Oblique Sit-Up",
  "decline sit up": "Crunch",
  "diamond push up": "Close-Grip Push-Up",
  "dip": "Bar Dip",
  "dips": "Bar Dip",
  "drag curls": "Drag Curl",
  "dumbbell back fly": "Reverse Dumbbell Flyes",
  "dumbbell bench press": "Dumbbell Chest Press",
  "dumbbell bicep curl": "Dumbbell Curl",
  "dumbbell bulgarian split squat": "Bulgarian Split Squat",
  "dumbbell clean": "Dumbbell Hang Clean",
  "dumbbell decline fly": "Dumbbell Chest Fly",
  "dumbbell fly": "Dumbbell Chest Fly",
  "dumbbell goblet squat": "Goblet Squat",
  "dumbbell incline bench press": "Incline Dumbbell Press",
  "dumbbell incline fly": "Dumbbell Chest Fly",
  "dumbbell kickbacks": "Dumbbell Lying Triceps Extension",
  "dumbbell preacher curls": "Dumbbell Preacher Curl",
  "dumbbell pull over": "Dumbbell Pullover",
  "dumbbell rear delt raise": "Reverse Dumbbell Flyes",
  "dumbbell seated single arm shoulder press": "Dumbbell Shoulder Press",
  "dumbbell skullcrusher": "Dumbbell Lying Triceps Extension",
  "dumbbell squat to shoulder press": "Dumbbell Squat",
  "dumbbell step up": "Step Up",
  "dumbbell stiff legged deadlift": "Stiff-Legged Deadlift",
  "dumbbell tricep extension": "Dumbbell Standing Triceps Extension",
  "dumbbell upright row": "Barbell Upright Row",
  "elbow to knee crunch": "Bicycle Crunch",
  "exercise ball crunch": "Crunch",
  "extra wide bench press": "Bench Press",
  "ez bar curls": "EZ Curl",
  "ez-bar curl": "EZ Curl",
  "ez-bar overhead tricep extension": "EZ Bar Lying Triceps Extension",
  "ez-bar preacher curl": "Barbell Preacher Curl",
  "face pulls": "Face Pull",
  "feet up bench": "Close-Grip Feet-Up Bench Press",
  "flutter kicks": "Lying Leg Raise",
  "front foot elevated split squat": "Bulgarian Split Squat",
  "front plank": "Plank",
  "front plate raise": "Plate Front Raise",
  "ghr": "Glute Ham Raise",
  "good mornings": "Good Morning",
  "hack squat": "Hack Squat Machine",
  "halting sumo deadlift": "Sumo Deadlift",
  "hammer curls": "Hammer Curl",
  "hammer up supinated down bicep curls": "Hammer Curl",
  "hammerstrength chest press": "Machine Chest Press",
  "hammerstrength decline chest press": "Machine Chest Press",
  "hammerstrength high row": "Seated Machine Row",
  "hammerstrength incline chest press": "Machine Chest Press",
  "hammerstrength iso row": "Seated Machine Row",
  "hammerstrength shoulder press": "Machine Shoulder Press",
  "hammerstrength shrug": "Barbell Shrug",
  "hamstring curls": "Lying Leg Curl",
  "hanging leg raises": "Hanging Leg Raise",
  "hanging oblique knee raise": "Hanging Windshield Wiper",
  "high bar squat": "Back Squat",
  "high knee": "Mountain Climbers",
  "high rows": "Seated Machine Row",
  "hip hinge": "Good Morning",
  "incline back extension": "Back Extension",
  "incline diamond pushup": "Incline Push-Up",
  "incline hammer curl": "Incline Dumbbell Curl",
  "incline push up": "Incline Push-Up",
  "kettlebell single arm farmer walk": "Farmers Walk",
  "kneeling 1 arm lat pulldown": "One-Handed Lat Pulldown",
  "l sit": "L-Sit",
  "l-sit": "L-Sit",
  "landmine cossack squat": "Cossack Squat",
  "lat pulldown": "Lat Pulldown With Pronated Grip",
  "lat pulldowns": "Lat Pulldown With Pronated Grip",
  "laying machine chest fly": "Machine Chest Fly",
  "leg extensions": "Leg Extension",
  "leg extensions (single leg)": "One-Legged Leg Extension",
  "leg press/hack squat": "Leg Press",
  "leg pull-in": "Lying Leg Raise",
  "leg raise": "Lying Leg Raise",
  "leg raises": "Lying Leg Raise",
  "low cable chest fly": "Standing Cable Chest Fly",
  "lunge": "Body Weight Lunge",
  "lunge with ankle grab": "Body Weight Lunge",
  "lunges": "Body Weight Lunge",
  "lying dumbbell skull crusher": "Dumbbell Lying Triceps Extension",
  "lying hamstrings curl": "Lying Leg Curl",
  "machine bench press": "Machine Chest Press",
  "machine fly": "Machine Chest Fly",
  "machine hip abductor": "Hip Abduction Machine",
  "machine hip adductor": "Hip Adduction Machine",
  "machine leg press": "Leg Press",
  "machine overhead tricep extension": "Machine Overhead Triceps Extension",
  "machine preacher curl": "Machine Bicep Curl",
  "machine rear delt fly": "Reverse Machine Fly",
  "machine row": "Seated Machine Row",
  "machine rows": "Seated Machine Row",
  "machine shoulder shrug": "Barbell Shrug",
  "machine tricep extension": "Machine Overhead Triceps Extension",
  "mb russian twists": "Oblique Sit-Up",
  "mountain climber": "Mountain Climbers",
  "neutral grip chinups": "Close-Grip Chin-Up",
  "neutral grip pull up": "Pull-Up With a Neutral Grip",
  "neutral grip pulldowns": "Lat Pulldown With Neutral Grip",
  "overhead db extensions": "Dumbbell Standing Triceps Extension",
  "overhead tricep extension": "Overhead Cable Triceps Extension (Low)",
  "overhead weighted sit up": "Sit-Up",
  "overhead/military press": "Overhead Press",
  "palms-up dumbbell wrist curl": "Dumbbell Wrist Curl",
  "pause back squat": "Pause Squat",
  "pause barbell decline bench press": "Decline Bench Press",
  "pause barbell incline bench press": "Incline Bench Press",
  "pause front squat": "Front Squat",
  "pause high bar squat": "Pause Squat",
  "plank jack": "Plank",
  "power clean and press": "Clean and Jerk",
  "power clean thruster": "Kettlebell Thrusters",
  "preacher curl": "Barbell Preacher Curl",
  "preacher curls": "Barbell Preacher Curl",
  "pull up": "Pull-Up",
  "pullups": "Pull-Up",
  "pulse lunge": "Body Weight Lunge",
  "push up": "Push-Up",
  "pushups w/ deep stretch": "Push-Up",
  "rack pulls": "Rack Pull",
  "rdls": "Romanian Deadlift",
  "rear delt fly machine": "Reverse Machine Fly",
  "rear foot elevated split squat": "Bulgarian Split Squat",
  "reverse crunch": "Lying Leg Raise",
  "reverse grip pull down": "Lat Pulldown With Supinated Grip",
  "romanian deadlift to high pull": "Romanian Deadlift",
  "russian twist": "Oblique Sit-Up",
  "scissor crossover kick": "Lying Leg Raise",
  "scissor kick": "Lying Leg Raise",
  "seated barbell shoulder press": "Seated Barbell Overhead Press",
  "seated dumbbell curl": "Dumbbell Curl",
  "seated machine calf press": "Seated Calf Raise",
  "shoulder press": "Overhead Press",
  "side bridge": "Side Plank",
  "side lunge": "Lateral Lunge Stretch",
  "side plank lift": "Dynamic Side Plank",
  "single arm high cable tricep extension": "Crossbody Cable Triceps Extension",
  "single arm lat pulldown": "One-Handed Lat Pulldown",
  "single arm low cable crossover fly": "Standing Cable Chest Fly",
  "single arm overhead press": "Overhead Press",
  "single arm preacher curl": "Barbell Preacher Curl",
  "single leg glute bridge": "One-Legged Glute Bridge",
  "single leg hip thrust": "One-Legged Hip Thrust",
  "single leg leg extension": "One-Legged Leg Extension",
  "single leg reverse hyper": "Reverse Hyperextension",
  "single leg straight forward bend": "Single Leg Romanian Deadlift",
  "single-arm dumbbell row on bench": "Chest-Supported Dumbbell Row",
  "sit up": "Sit-Up",
  "skullcrusher": "Barbell Lying Triceps Extension",
  "sl leg press/hack squat": "Leg Press",
  "smith machine bent over row": "Smith Machine One-Handed Row",
  "smith machine calf raise": "Standing Calf Raise",
  "smith machine glute bridge": "Smith Machine Hip Thrust",
  "smith machine one-arm upright row": "Barbell Upright Row",
  "smith machine overhead shoulder press": "Seated Smith Machine Shoulder Press",
  "smith machine shrug": "Barbell Shrug",
  "smith machine stiff-legged deadlift": "Smith Machine Romanian Deadlift",
  "smith machine upright row": "Barbell Upright Row",
  "split squat (glute emphasis)": "Bulgarian Split Squat",
  "split squat (quad emphasis)": "Squat",
  "ssb squat": "Safety Bar Squat",
  "standing barbell calf raise": "Standing Calf Raise",
  "standing cable core twist": "Core Twist",
  "standing dumbbell tricep extension": "Dumbbell Standing Triceps Extension",
  "standing hip circle": "Hip Thrust",
  "standing machine calf press": "Standing Calf Raise",
  "static lunge": "Body Weight Lunge",
  "step ups": "Step Up",
  "stiff-legged barbell good morning": "Good Morning",
  "straight-arm pulldown": "Straight Arm Lat Pulldown",
  "super high rows": "Seated Machine Row",
  "superman": "Superman Raise",
  "superman hold": "Superman Raise",
  "tempo stiff leg deadlift (5:0:0)": "Stiff-Legged Deadlift",
  "tempo wide grip bench (5:0:0)": "Bench Press",
  "toe touchers": "Crunch",
  "toes to bar": "Hanging Leg Raise",
  "trap bar deadlift": "Trap Bar Deadlift With High Handles",
  "tricep push up": "Close-Grip Push-Up",
  "tricep pushdown": "Tricep Pushdown With Bar",
  "tuck crunch": "Crunch",
  "upright row": "Barbell Upright Row",
  "upright rows": "Barbell Upright Row",
  "v-bar pulldown": "Lat Pulldown With Neutral Grip",
  "vertical knee raise": "Hanging Knee Raise",
  "vertical leg raise": "Hanging Leg Raise",
  "walkout to push up": "Push-Up",
  "weighted situps": "Sit-Up",
  "wide grip lat pulldown": "Lat Pulldown With Pronated Grip",
  "wide grip pull up": "Pull-Up",
  "wide grip seated row": "Cable Wide Grip Seated Row",
  '1" conv deficit deadlift': "Conventional Deadlift",
  '1" sumo deficit deadlift': "Sumo Deadlift",
  '3" conv block pull': "Rack Pull",
};
